"""init

Revision ID: 0e546792eab3
Revises: 
Create Date: 2025-02-02 16:34:56.325805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e546792eab3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('proj_id', sa.UUID(), nullable=False),
    sa.Column('projname', sa.String(), nullable=False),
    sa.Column('picture_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('proj_id'),
    sa.UniqueConstraint('picture_path'),
    sa.UniqueConstraint('projname')
    )
    op.create_table('tdim_files',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('picture_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('date_upload', sa.Date(), nullable=False),
    sa.Column('proj_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('filepath')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tdim_files')
    op.drop_table('projects')
    # ### end Alembic commands ###
