# Используем официальный образ Python
FROM python:3.10-slim

# Установка зависимостей
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем приложение
COPY . .

# Запускаем приложение
CMD ["python3", "app.py", "--host", "0.0.0.0", "--port", "8000"]
